import argparse
from pathlib import Path

from app.scripts.import_topics import parse_topics


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_sql(source: Path) -> str:
    topics = parse_topics(source)
    statements = [
        "-- Reda1000IA: catálogo de temas ENEM para Supabase",
        "begin;",
        "",
        "create table if not exists public.essay_topics (",
        "  id bigint generated by default as identity primary key,",
        "  title varchar(500) not null unique,",
        "  category varchar(200) not null,",
        "  active boolean not null default true,",
        "  created_at timestamptz not null default now()",
        ");",
        "",
        "create index if not exists ix_essay_topics_active on public.essay_topics (active);",
        "alter table public.essay_topics enable row level security;",
        "drop policy if exists essay_topics_public_read on public.essay_topics;",
        "create policy essay_topics_public_read on public.essay_topics for select to anon, authenticated using (active = true);",
        "",
    ]
    batch_size = 200
    for start in range(0, len(topics), batch_size):
        batch = topics[start:start + batch_size]
        values = ",\n".join(
            f"  ({quote(topic['title'])}, {quote(topic['category'])}, true)" for topic in batch
        )
        statements.extend([
            "insert into public.essay_topics (title, category, active) values",
            values,
            "on conflict (title) do update set category = excluded.category, active = true;",
            "",
        ])
    statements.extend([
        "commit;",
        "",
        "-- Conferência: deve retornar 994 temas ativos.",
        "select count(*) as temas_ativos from public.essay_topics where active = true;",
        "",
        "-- Exemplo de sorteio:",
        "select id, title, category from public.essay_topics where active = true order by random() limit 1;",
    ])
    return "\n".join(statements) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(build_sql(args.source), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
